"""add_is_admin

Revision ID: 402cad2c9faa
Revises: 4ebfb4a6e021
Create Date: 2026-06-04 22:54:56.202196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402cad2c9faa'
down_revision = '4ebfb4a6e021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
